### ISSUE TITLE
XFCE 4.12.2 not resizing when window is maximized

### ISSUE THREAD

**Issue by dol** [mjs7231/pygrid#2]
If a window is maximized in XFCE (current version 4.12.2 / Xubuntu 16.04) the pyGrid commands are not working. Only if the window is unmaximized, the pyGrid keyboard bindings are affective.

**Comment by mjs7231** [comment]
Thanks, same thing is happening for me in Gnome Shell. Looks like I need to unmaximize it first.

**Comment by mjs7231** [comment]
This fixed it for me. If it doesn't work on your end please let me know and I'll reopen it.

commit 21fe905e212a1ff58f73da5311a4ec4a804cdae3
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Mon Oct 10 11:18:50 2016 -0400
Unmaximize the window before moving it

**Comment by dol** [comment]
Seems to work. Thx
